branches:
  only:
  - master

language: bash
arch: amd64
os: linux
dist: bionic
sudo: required

install:
- sudo apt-get update -y

# Needed for unit testing with qt https://github.com/pytest-dev/pytest-qt/issues/293
- sudo apt-get install -y xvfb libxkbcommon-x11-0
- sudo Xvfb :1 -screen 0 1024x768x24 </dev/null &
- export DISPLAY=":1"

# Start setting up stuff for GS
- sudo apt-get install -y python3.7 python3-pip python3.7-venv python3-tk libpython3.7-dev
- python3.7 --version
- python3.7 -m pip install --upgrade pip setuptools wheel
- python3.7 -m venv venv
- source venv/bin/activate
- python --version
- python -c "import sys; print(sys.executable)"
- pip install -r requirements.txt
- echo "$MAPBOX_API_KEY" > apikey.txt

script:
- python -m pytest
